# constants/states.py

# مراحل ثبت‌نام کاربر
SELECT_GENDER, SELECT_PROVINCE, SELECT_CITY = range(3)

# مراحل پروفایل
AWAIT_NAME, AWAIT_AGE, SELECT_SCHOOL, AWAIT_PHONE = range(3, 7)

# مراحل ادمین
AWAIT_CHANNEL_BUTTON_TEXT, AWAIT_SCHOOL_PROVINCE, AWAIT_SCHOOL_CITY, AWAIT_SCHOOL_NAMES = range(7, 11)